### ISSUE TITLE
Power pin

### ISSUE THREAD

**Issue by 1602** [danjperron/PicoDHT22#4]
Could you please clarify usage of power pin? I see in the example it is set to 14, but I only have data pin connected to GP15 and nothing for GP14. I'm following this scheme:
![image](https://user-images.githubusercontent.com/184172/126042407-8885049b-f452-443e-8c1e-39703db9a64d.png)
(image credit: https://www.tomshardware.com/how-to/raspberry-pi-pico-weather-station)

**Comment by danjperron** [comment]
Hi Anatoiiy,

   The power pin is not needed. Essentially is to reduce power and reset the DHT22. Sometimes my DHT22 hangs and it was the only way to reset it.


Instead of using the VCC to power up the DHT22 use on of the GPIO . Don't forget to put the pull up on the same GPIO you are using for power.
Best regards, 

Daniel Perron

**Comment by 1602** [comment]
Thank you, Daniel! I tried to use GPIO 14 as a power source for the sensor and it works as expected. Additionally thank you so very much for sharing your code, not only it helps to progress with my first project on raspberry pi pico, but also helps to learn how to deal with PIO.
